apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-volume
spec:
    capacity:
        # RESERVE 5 GIGABYTES FOR VOLUME
        storage: 5Gi
    volumeMOde: Filesystem
    # READ WRITE, READ ONLY ETC 
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: slow
    mountOptions:
        - hard
        - nfsvers=4.0
    # NFS DETAILS
    nfs:
        path: /path/to/dir
        server: nfs-server-ip