apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-deployment
    labels:
        app: db-deployment

# DEPLOYMENT SPECS
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db-deployment

    # POD BLUEPRINT
    template:
        metadata:
            labels:
                app: db-deployment
        spec:
            containers:
                -   name: db-pod
                    image: mongo
                    ports:
                        - containerPort: 27017
                        
                    # ENVIRONMENT VARIABLES FOR MONGO DB
                    env:
                        # DB USERNAME
                        -   name: MONGO_INITDB_ROOT_USERNAME
                            valueFrom:
                                secretKeyRef:
                                    name: private-vars
                                    key: db-username
                        # DB PASSWORD
                        -   name: MONGO_INITDB_ROOT_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: private-vars
                                    key: db-password