apiVersion: v1
kind: Service
metadata:
    name: db-service

# SERVICE PROPS
spec:
    selector:
        app: db-deployment
    ports:
        -   protocol: TCP

            # SERVICE PORT
            port: 27017
            
            # POD PORT
            targetPort: 27017