apiVersion: v1
kind: Service
metadata:
    name: db-serv

# SERVICE PROPS
spec:
    selector:
        app: db-depl
    ports:
        -   protocol: TCP
            # SERVICE PORT
            port: 27017
            # POD PORT
            targetPort: 27017