apiVersion: apps/v1
kind: Deployment
metadata:
    name: express-deployment
    labels:
        app: express-deployment

# DEPLOYMENT SPECS
spec:
    replicas: 1
    selector:
        matchLabels:
            app: express-deployment

    # POD BLUEPRINT
    template:
        metadata:
            labels:
                app: express-deployment
        spec:
            containers:
                -   name: express-pod
                    image: mongo-express
                    ports:
                        - containerPort: 8081

                    # ENVIRONMENT VARIABLES FOR MONGO EXPRESS
                    env:
                        # DB USERNAME
                        -   name: ME_CONFIG_MONGODB_ADMINUSERNAME
                            valueFrom:
                                secretKeyRef:
                                    name: private-vars
                                    key: db-username
                        # DB PASSWORD
                        -   name: ME_CONFIG_MONGODB_ADMINPASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: private-vars
                                    key: db-password
                        # DB SERVER
                        -   name: ME_CONFIG_MONGODB_SERVER
                            valueFrom:
                                configMapKeyRef:
                                    name: public-vars
                                    key: db-server